### PR TITLE
Remoteloader speed effenceny improvment

### PR DESCRIPTION
**Pull request by without-ordinary**
Remoteloader will no longer always wait 3 seconds after using the last slave, instead it will use the next slave if it has been more than 3 seconds since the last time it was used, if not, it will set a retry timer for the remaining time.

### CODE REVIEW

**Comment by without-ordinary** [comment]
Relates to https://github.com/JasXSL/GoThongs/issues/85

**Comment by without-ordinary** [comment]
Found some instability. Investigating.

**Comment by without-ordinary** [comment]
Nevermind, found the problem. SL weirdness again, HUD script assets are reverting to something old version on attach. Welp, that looks like something to report to LL.

**Comment by without-ordinary** [comment]
There still may be some issue with this, but with the attachment weirdness, it's making it hard to tell what's causing the problem. More testing needed. :-1:

**Comment by without-ordinary** [comment]
Ok, the weird HUD script reverting is unrelated. I cannot figure out why it happens nor can I reliably repo it. I want to say its asset sync taking too long, but I was first getting it happening between logins, so no idea. Its making testing a pain because...

On attach, this rev of remoteloader will get stuck processing its queue (in my current setup/use) on the 13th load when the got hud is attached and initial weapon load occurs. If reset, it will be fine. Adding some debug outputs hints that it may actually be a race condition where another load is inserted into the queue before next() is called from the previous load call. Very much an edge case scenario and from what I can tell, could have been happening before as well under certain circumstances.

I added even more debugs to try to narrow down exactly when this happens, but the one additional debug changed the timing just enough to break my repo. That definitely suggested race condition to me. Gonna rework the next pumping.

**Comment by without-ordinary** [comment]
I'm an idiot. I see the problem now.

**Comment by JasXSL** [comment]
The rollback on attachments have been a thing since forever. To prevent it, wait 10-30 sec after detaching, then make a copy of it.

**Pull request closed without merging**
